name: Build and deploy Sentiment Analysis App to Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: air-paradis-sentiment-api
  PYTHON_VERSION: '3.9'
  APPINSIGHTS_INSTRUMENTATION_KEY: '${{ secrets.APPINSIGHTS_INSTRUMENTATION_KEY }}'

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Prepare deployment package
        run: |
          # Create deployment script
          echo "Creating deployment scripts..."
          chmod +x deploy/prepare_deployment.sh
          ./deploy/prepare_deployment.sh

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Set up App Insights alert rule
        run: |
          # Set up alert rule for consecutive errors
          echo "Setting up Application Insights alert rule for model errors..."
          az monitor metrics alert create \
            --name "ConsecutiveModelErrors" \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --scopes ${{ secrets.APPINSIGHTS_RESOURCE_ID }} \
            --condition "count customEvents where name = 'IncorrectPrediction' > 3 where timeGrain = PT5M" \
            --window-size 5m \
            --evaluation-frequency 1m \
            --action ${{ secrets.ACTION_GROUP_ID }} \
            --description "Alert when the model makes 3 consecutive incorrect predictions" \
            --severity 2
        continue-on-error: true

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './deployment_package'