name: Build and deploy Sentiment Analysis App to Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: air-paradis-sentiment-api
  PYTHON_VERSION: '3.9'
  APPINSIGHTS_INSTRUMENTATION_KEY: '9af56b4d-4ad5-4643-ba29-41d154893ad4'
  RESOURCE_GROUP: 'p06-AirParadisResources'
  APP_INSIGHTS_NAME: 'air-paradis-sentiment-monitoring'

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: |
          python -m pytest tests/

      - name: Create deployment package
        run: |
          # Create a directory for the deployment package
          mkdir -p deployment_package
          
          # Copy the required files to the deployment package
          cp -r api.py app.py application.py init_models.py startup.sh requirements.txt runtime.txt .streamlit tests deployment_package/
          
          # Create necessary directories and copy models if they exist
          mkdir -p deployment_package/models
          if [ -d "models/bert" ]; then
            cp -r models/bert deployment_package/models/
            echo "Modèle BERT existant copié dans le package de déploiement"
          else
            mkdir -p deployment_package/models/bert
            echo "Répertoire models/bert créé (vide)"
          fi
          
          # Copy preloaded models if they exist
          if [ -d "preloaded_models" ]; then
            cp -r preloaded_models deployment_package/
            echo "Modèles préchargés copiés dans le package de déploiement"
          fi
          
          # Create logs directory
          mkdir -p deployment_package/logs
          
          # Copy the logo if it exists
          cp -r air-paradis-logo.png deployment_package/ || echo "Logo file not found, continuing..."
          
          # Create a web.config file for Azure App Service
          echo '<?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <handlers>
                <add name="PythonHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
              </handlers>
              <httpPlatform processPath="bash" arguments="startup.sh" requestTimeout="00:04:00" startupTimeLimit="120" startupRetryCount="3" stdoutLogEnabled="true" stdoutLogFile="logs\api.log">
                <environmentVariables>
                  <environmentVariable name="PYTHONUNBUFFERED" value="1"/>
                  <environmentVariable name="APPINSIGHTS_INSTRUMENTATION_KEY" value="${{ env.APPINSIGHTS_INSTRUMENTATION_KEY }}"/>
                </environmentVariables>
              </httpPlatform>
            </system.webServer>
          </configuration>' > deployment_package/web.config

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './deployment_package'